# Generated by Django 5.0 on 2023-12-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images'),
        ),
    ]
